name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ] # Trigger on push to main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true # MANDATORY: This tells the action to download the actual LFS files

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: Build
          branch: gh-pages
